name: CD for Pull Requests

on:
  push:
    branches-ignore: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Yarn Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Yarn Export
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: export
        
    - name: Repair File Paths
      run: | 
        sudo find ./out -type f -name "*.html" -exec sed -i 's/\/_next/.\/_next/g' {} +

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.CD_DEPLOY_KEY }}
        external_repository: SYDE-25/Class-Profile-CI
        publish_branch: main
        publish_dir: ./out
        destination_dir: ./${{ GITHUB_HEAD_REF }}
        keep_files: true
        
#     - name: PR Comment
#       uses: github-actions-up-and-running/pr-comment@v1.0.1
#       with:
#         repo-token: ${{ secrets.GITHUB_TOKEN }}
#         message: Deployed at https://syde-25.github.io/Class-Profile-CI/${{ GITHUB_HEAD_REF }}

    - uses: actions/github-script@v3
      with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ('Deployed at https://syde-25.github.io/Class-Profile-CI/' + process.env.GITHUB_HEAD_REF)
            })
