name: CD for Pull Requests

on:
  push:
    branches-ignore: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Get the current branch name
      shell: bash
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      id: myref
      
    - name: Install Dependencies
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install

    - name: Yarn Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build

    - name: Yarn Export
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: export
        
    - name: Repair File Paths
      run: | 
        sudo find ./out -type f -name "*.html" -exec sed -i 's/\/_next/.\/_next/g' {} +

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.CD_DEPLOY_KEY }}
        external_repository: SYDE-25/Class-Profile-CI
        publish_branch: main
        publish_dir: ./out
        destination_dir: ./${{ ${{ steps.myref.outputs.branch }} }}
        keep_files: true

    - name: Comment on PR
      uses: unsplash/comment-on-pr@master
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          msg: Deployed at https://syde-25.github.io/Class-Profile-CI/${{ ${{ steps.myref.outputs.branch }} }}
          check_for_duplicate_msg: true
