name: CD for Pull Requests

on:
  pull_request:
    branches-ignore: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2.1.5
      
    - name: Install Dependencies
      run: yarn install

    - name: Yarn Build
      run: yarn build

    - name: Yarn Export
      run: yarn export
        
    # - name: Repair File Paths
    #   run: | 
    #     sudo find ./out -type f -name "*.html" -exec sed -i 's/\/_next/.\/_next/g' {} +

    - name: Get the current branch name
      shell: bash
      run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
      id: branchname

    - name: Deploy to CD Repo
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.CD_DEPLOY_KEY }}
        external_repository: SYDE-25/Class-Profile-CD
        publish_branch: main
        publish_dir: ./out
        destination_dir: ./${{ steps.branchname.outputs.branch }}
        keep_files: true

    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@master
      with:
        message: Deployed at https://syde-25.github.io/Class-Profile-CD/${{ steps.branchname.outputs.branch }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}